version: '3.4'
services:
  keep-client.public.dappnode.eth:
    build: ./build
    environment:
      - HTTP_RPC_URL
      - KEEP_ETHEREUM_PASSWORD
      - LOG_LEVEL=debug
      - PEERS
      - WS_RPC_URL
    image: 'keep-client.public.dappnode.eth:0.1.0'
    restart: always
    volumes:
      - "persistence:/mnt/persistence"
      - "keystore:/mnt/keystore"

volumes:
  persistence: {}
  keystore: {}
